version: 0.2

env:
  variables:
    AWS_REGION: ap-northeast-2
    IMAGE_REPO_NAME: fitspot-app   # ECR 리포지토리 이름 (한 곳으로 통일)
    IMAGE_TAG: latest
    CONTAINER_NAME: app1           # ECS 태스크 정의의 container name과 정확히 동일

phases:
  pre_build:
    commands:
      - set -euo pipefail
      - echo "Normalize gradlew & build"
      - sed -i 's/\r$//' ./gradlew || true
      - chmod +x ./gradlew
      - ./gradlew clean build
      - ls -al build/libs || true

      - echo "Resolve account/registry"
      - REGION="${AWS_REGION:-${AWS_DEFAULT_REGION:-ap-northeast-2}}"
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_REGISTRY="${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com"
      - REPOSITORY_URI="${ECR_REGISTRY}/${IMAGE_REPO_NAME}"
      - echo "DEBUG REGION=$REGION"
      - echo "DEBUG ACCOUNT_ID=$ACCOUNT_ID"
      - echo "DEBUG ECR_REGISTRY=$ECR_REGISTRY"
      - echo "DEBUG REPOSITORY_URI=$REPOSITORY_URI"
      - aws --version

      - |
        echo "ECR login (retry up to 5)"
        for i in 1 2 3 4 5; do
          PASS=$(aws ecr get-login-password --region "$REGION") || true
          if [ -n "${PASS:-}" ] && [ ${#PASS} -gt 100 ]; then
            echo "$PASS" | docker login --username AWS --password-stdin "$ECR_REGISTRY" && break
          fi
          echo "login failed (attempt $i). retry in 3s..."
          sleep 3
        done

  build:
    commands:
      - echo "Docker build / tag / push"
      - docker build -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} .
      - docker tag  ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${REPOSITORY_URI}:${IMAGE_TAG}
      - docker push ${REPOSITORY_URI}:${IMAGE_TAG}
      - IMAGE_URI=${REPOSITORY_URI}:${IMAGE_TAG}
      - echo "DEBUG IMAGE_URI=$IMAGE_URI"

  post_build:
    commands:
      - echo "Generate imagedefinitions.json for ${CONTAINER_NAME}"
      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$IMAGE_URI" > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

cache:
  paths:
    - '/root/.gradle/**/*'